# Generated by Django 4.0.4 on 2022-05-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('autor', models.CharField(max_length=80)),
                ('anoPublicacao', models.CharField(max_length=4)),
                ('url', models.CharField(max_length=2048)),
            ],
        ),
    ]
